import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.scss';


const geistRoboto = Roboto({
    variable: '--font-roboto-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistRoboto.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
